[theme]
base="dark"
primaryColor="#1DB954"                # Spotify Green
backgroundColor="#121212"             # Spotify's main background black
secondaryBackgroundColor="#1E1E1E"    # A slightly lighter gray for cards/sidebars
textColor="#FFFFFF"                   # White text for high contrast
font="sans serif"
