[theme]
base="light"
primaryColor="#1E88E5"                 # A more modern, vibrant blue
backgroundColor="#F0F2F6"             # A soft, neutral background
secondaryBackgroundColor="#FFFFFF"    # White for cards and sidebars
textColor="#31333F"                   # A dark gray for better readability
font="sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[client]
toolbarMode = "minimal"
